name: Build Release Assets
on:
  push:
    tags:
      - '*'

jobs:
  build-windows-x86-64:
    runs-on: windows-2019
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Get Version Number
        shell: bash
        id: version_number
        run: .github/actions/get-version.sh windows x86-64

      - name: Build
        shell: bash
        env:
          BB_ARTIFACT_NAME: ${{ steps.version_number.outputs.BB_ARTIFACT_NAME }}
          BB_VERSION: ${{steps.version_number.outputs.BB_VERSION}}
        run: |
          
          mkdir build && cd build
          cmake ..
          bash -e -o pipefail ../extract-version.sh
          cat ../src/Version.h
          cmake --build . --target bladebit --config Release

          # Ensure bladebit version matches expected version
          bb_version="$(./Release/bladebit.exe --version | xargs)"

          if [[ "$bb_version" != "$BB_VERSION" ]]; then
              >&2 echo "Incorrect bladebit version. Got but '$bb_version' expected '$BB_VERSION'."
              exit 1
          fi
          
          mkdir ../bin
          cd Release
          7z.exe a -tzip ../../bin/${BB_ARTIFACT_NAME} bladebit.exe
          ls -la ../../bin

      - name: Upload Artifact Windows x86-64
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.version_number.outputs.BB_ARTIFACT_NAME }}
          path: ${{ github.workspace }}/bin/${{ steps.version_number.outputs.BB_ARTIFACT_NAME }}
          if-no-files-found: error


      - name: Upload a Build Artifact to release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/Release/bladebit.exe
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
